package programapermutacionestadistica;

import javax.swing.JOptionPane;

public class permutacion extends javax.swing.JFrame {

    public permutacion() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("Permutación");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        botonPermutacion = new javax.swing.JButton();
        etiquetaNombrePrograma2 = new javax.swing.JLabel();
        etiquetaNombrePrograma1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        campoPermutacion = new javax.swing.JTextField();
        botonPermutacion1 = new javax.swing.JButton();
        etiquetaNombrePrograma3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel1.setBackground(new java.awt.Color(153, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonPermutacion.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        botonPermutacion.setText("Calcular");
        botonPermutacion.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botonPermutacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPermutacionActionPerformed(evt);
            }
        });
        jPanel1.add(botonPermutacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 540, 150, 50));

        etiquetaNombrePrograma2.setFont(new java.awt.Font("Century Gothic", 1, 48)); // NOI18N
        etiquetaNombrePrograma2.setForeground(new java.awt.Color(255, 0, 0));
        etiquetaNombrePrograma2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaNombrePrograma2.setText("Permutación");
        etiquetaNombrePrograma2.setAlignmentY(0.0F);
        etiquetaNombrePrograma2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(etiquetaNombrePrograma2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, -1, -1));

        etiquetaNombrePrograma1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        etiquetaNombrePrograma1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaNombrePrograma1.setText("n! =");
        etiquetaNombrePrograma1.setAlignmentY(0.0F);
        etiquetaNombrePrograma1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(etiquetaNombrePrograma1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 500, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/formulaPermutacion.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 400, 1071, -1));
        jPanel1.add(campoPermutacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 500, 100, 30));

        botonPermutacion1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        botonPermutacion1.setText("Menú Principal");
        botonPermutacion1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botonPermutacion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPermutacion1ActionPerformed(evt);
            }
        });
        jPanel1.add(botonPermutacion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 540, 170, 50));

        etiquetaNombrePrograma3.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        etiquetaNombrePrograma3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaNombrePrograma3.setText("<html>\n<p> <center>Es una forma de ordenar o arreglar la totalidad de los elementos de un conjunto;</center></p>\n<p><center>también se puede considerar como un conjunto de elementos extraídos</center></p>\n<p><center>en un orden específico y sin reemplazo de un conjunto igual o mayor.</center></p>\n</html>\n");
        etiquetaNombrePrograma3.setAlignmentY(0.0F);
        etiquetaNombrePrograma3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        etiquetaNombrePrograma3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(etiquetaNombrePrograma3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1443, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonPermutacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPermutacionActionPerformed

        try {
            int numeroIntroducido, factorial = 1;
            numeroIntroducido = Integer.parseInt(campoPermutacion.getText());
            for (int i = numeroIntroducido; i > 0; i--) {
                factorial = factorial * i;
            }

            JOptionPane.showMessageDialog(null, "El factorial del numero " + numeroIntroducido + " es " + factorial, "Resultado", JOptionPane.PLAIN_MESSAGE);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Debe ingresar un NUMERO para calcular su factorial en el campo de texto", "Error en el valor introducido", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_botonPermutacionActionPerformed

    private void botonPermutacion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPermutacion1ActionPerformed
        menuPrincipal a = new menuPrincipal();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botonPermutacion1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(permutacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(permutacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(permutacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(permutacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new permutacion().setVisible(true);
            }

        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonPermutacion;
    private javax.swing.JButton botonPermutacion1;
    private javax.swing.JTextField campoPermutacion;
    private javax.swing.JLabel etiquetaNombrePrograma1;
    private javax.swing.JLabel etiquetaNombrePrograma2;
    private javax.swing.JLabel etiquetaNombrePrograma3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
