package programapermutacionestadistica;

import javax.swing.JOptionPane;

public class permutacionConRepeticion extends javax.swing.JFrame {

    public permutacionConRepeticion() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("Permutación Con Repetición");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        botonPermutacion = new javax.swing.JButton();
        etiquetaNombrePrograma2 = new javax.swing.JLabel();
        etiquetaNombrePrograma1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        campoN = new javax.swing.JTextField();
        botonPermutacion1 = new javax.swing.JButton();
        etiquetaNombrePrograma3 = new javax.swing.JLabel();
        etiquetaNombrePrograma4 = new javax.swing.JLabel();
        etiquetaNombrePrograma5 = new javax.swing.JLabel();
        etiquetaNombrePrograma6 = new javax.swing.JLabel();
        numeroDeR = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel1.setBackground(new java.awt.Color(153, 255, 255));

        botonPermutacion.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        botonPermutacion.setText("Calcular");
        botonPermutacion.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botonPermutacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPermutacionActionPerformed(evt);
            }
        });

        etiquetaNombrePrograma2.setFont(new java.awt.Font("Century Gothic", 1, 48)); // NOI18N
        etiquetaNombrePrograma2.setForeground(new java.awt.Color(255, 0, 0));
        etiquetaNombrePrograma2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaNombrePrograma2.setText("Permutación Con Repetición");
        etiquetaNombrePrograma2.setAlignmentY(0.0F);
        etiquetaNombrePrograma2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        etiquetaNombrePrograma1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        etiquetaNombrePrograma1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaNombrePrograma1.setText("n =");
        etiquetaNombrePrograma1.setAlignmentY(0.0F);
        etiquetaNombrePrograma1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/formulaPermutacionConRepeticion.png"))); // NOI18N

        botonPermutacion1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        botonPermutacion1.setText("Menú Principal");
        botonPermutacion1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botonPermutacion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPermutacion1ActionPerformed(evt);
            }
        });

        etiquetaNombrePrograma3.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        etiquetaNombrePrograma3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaNombrePrograma3.setText("<html>\n<p> <center>Se aplica la siguiente fórmula en el caso de que algunos elementos se repitan.</center></p>\n</html>\n");
        etiquetaNombrePrograma3.setAlignmentY(0.0F);
        etiquetaNombrePrograma3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        etiquetaNombrePrograma3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        etiquetaNombrePrograma4.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        etiquetaNombrePrograma4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaNombrePrograma4.setText("r =");
        etiquetaNombrePrograma4.setAlignmentY(0.0F);
        etiquetaNombrePrograma4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        etiquetaNombrePrograma5.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        etiquetaNombrePrograma5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaNombrePrograma5.setText("n = La cantidad total de elementos");
        etiquetaNombrePrograma5.setAlignmentY(0.0F);
        etiquetaNombrePrograma5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        etiquetaNombrePrograma6.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        etiquetaNombrePrograma6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaNombrePrograma6.setText("r1,r2,... rn = cada r representa la cantidad de veces que se repite dicho elemento");
        etiquetaNombrePrograma6.setAlignmentY(0.0F);
        etiquetaNombrePrograma6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        numeroDeR.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(botonPermutacion1)
                        .addGap(458, 458, 458)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonPermutacion, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(etiquetaNombrePrograma4)
                                    .addComponent(etiquetaNombrePrograma1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(campoN, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                                    .addComponent(numeroDeR, 0, 80, Short.MAX_VALUE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(etiquetaNombrePrograma3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(601, 601, 601)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(292, 292, 292)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(etiquetaNombrePrograma6)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(224, 224, 224)
                                .addComponent(etiquetaNombrePrograma5))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(369, 369, 369)
                        .addComponent(etiquetaNombrePrograma2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(etiquetaNombrePrograma2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(etiquetaNombrePrograma3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(etiquetaNombrePrograma5)
                .addGap(1, 1, 1)
                .addComponent(etiquetaNombrePrograma6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(etiquetaNombrePrograma1)
                    .addComponent(campoN, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(etiquetaNombrePrograma4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(numeroDeR))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonPermutacion, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonPermutacion1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonPermutacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPermutacionActionPerformed

        try {
            int n, r, factorialn = 1, denominador, factorialdenominador = 1, variacion;
            n = Integer.parseInt(campoN.getText());
            r = Integer.parseInt(numeroDeR.getSelectedItem().toString());
            for (int i = n; i > 0; i--) {
                factorialn = factorialn * i;
            }

            denominador = n - r;

            for (int i = denominador; i > 0; i--) {
                factorialdenominador = factorialdenominador * i;
            }

            variacion = factorialn / factorialdenominador;

            JOptionPane.showMessageDialog(null, "La variación con los numeros insertados como n= " + n + " y r= " + r + " dan como resultado " + variacion, "Resultado", JOptionPane.PLAIN_MESSAGE);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Debe ingresar un NUMERO para calcular su factorial en el campo de texto", "Error en el valor introducido", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_botonPermutacionActionPerformed

    private void botonPermutacion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPermutacion1ActionPerformed
        menuPrincipal a = new menuPrincipal();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botonPermutacion1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(permutacionConRepeticion.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(permutacionConRepeticion.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(permutacionConRepeticion.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(permutacionConRepeticion.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new permutacionConRepeticion().setVisible(true);
            }

        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonPermutacion;
    private javax.swing.JButton botonPermutacion1;
    private javax.swing.JTextField campoN;
    private javax.swing.JLabel etiquetaNombrePrograma1;
    private javax.swing.JLabel etiquetaNombrePrograma2;
    private javax.swing.JLabel etiquetaNombrePrograma3;
    private javax.swing.JLabel etiquetaNombrePrograma4;
    private javax.swing.JLabel etiquetaNombrePrograma5;
    private javax.swing.JLabel etiquetaNombrePrograma6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JComboBox<String> numeroDeR;
    // End of variables declaration//GEN-END:variables

    public void getNumeroDeR(String boxNumeroDeR) {
        String NumeroDeR = boxNumeroDeR;
    }
}
